apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-web-label
  template:
    metadata: 
      labels:
        app: nginx-web-label
    spec:
      containers:
      - name: nginx-container
        image: minseung12/nginx:bfbd9a320e7c82fe57b996ef0adbcd11fdc03ec3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nginx-web-label
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
